---
title: "R Notebook"
output: html_notebook
---

# Distribution of tokens

```{r}
library(vcdExtra)
library(lattice)
library(effects)
library(vcd)

all_data <- read.csv("./data/all_data.csv", stringsAsFactors = T)

str(all_data)
```

## (Year) by Verb

```{r}
structable(verb ~ year_bins_40, all_data)
```

## (Year + Variety) by Verb

```{r}
structable(verb + variety ~ year_bins_40, all_data)
```

## (Year + Negation) by Verb

```{r}
structable(verb + negation ~ year_bins_40, all_data)
```
## (Year + Transitivity) by Verb

```{r}
structable(verb + transitivity_short ~ year_bins_40, all_data)
```


## (Year + Genre) by Verb

```{r}
structable(verb + genre_short ~ year_bins_40, all_data)
```


# Focus on varieties

## (Year + Negation) by Variety and Verb

```{r}
structable(verb + variety + negation ~ year_bins_40, all_data)
```

## (Year + Transitivity) by Variety and Verb

```{r}
structable(verb + variety + transitivity_short ~ year_bins_40, all_data)
```

## (Year + Genre) by Variety and Verb

```{r}
structable(verb + variety + genre_short ~ year_bins_40, all_data)
```

