---
title: "Untitled"
output: html_document
---


# Models for long-term diachronic perspective

```{r}
all_data <- read.csv("./data/all_data.csv", stringsAsFactors = T)
```

## Loss of interpretators

### Deceive

```{r}
m_long_deceive <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation, 
  data=all_data, subset=verb == "deceive", family="binomial")

arm::display(m_long_deceive)
```

```{r fig.width=10, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=4, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=4, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_long_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=4, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_long_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=4, more=F)),
  main="Transitivity", xlab="", ylab="")

```


### Delude

```{r}
m_long_delude <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation, 
  data=all_data, subset=verb == "delude", family="binomial")

arm::display(m_long_delude)
```

```{r fig.width=10, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=4, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=4, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_long_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=4, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_long_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=4, more=F)),
  main="Transitivity", xlab="", ylab="")

```


### Fool

```{r}
m_long_fool <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation, 
  data=all_data, subset=verb == "fool", family="binomial")

arm::display(m_long_fool)
```

```{r fig.width=10, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=4, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=4, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_long_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=4, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_long_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=4, more=F)),
  main="Transitivity", xlab="", ylab="")

```


## Replacement of nominal by verbal interpretators

```{r}
str(all_data)
all_data_replacement <- subset(all_data, interpretator_type != "none")
all_data_replacement$interpretator_verbal <- ifelse(all_data_replacement$interpretator_type == "verbal", 1, 0)
all_data_replacement <- droplevels(all_data_replacement)
str(all_data_replacement)
```

### List of interpretators

- Interpretators ordered by overall occurrence rate
- Borken down by verb and (major) period

```{r}
# List of interpretators
all_data_replacement$interpretator_ordered <- all_data_replacement$interpretator
all_data_replacement$interpretator_ordered <- factor(
  all_data_replacement$interpretator_ordered,
  levels=names(sort(table(all_data_replacement$interpretator), decreasing=T)),
  ordered=T
)

vcd::structable(verb + year_bins_100 ~ interpretator_ordered, all_data_replacement)
```


### Deceive

```{r}
m_long_deceive_replacement <- glm(
  interpretator_verbal ~ year_c + variety, 
  data=all_data_replacement, subset=verb == "deceive", family="binomial")

arm::display(m_long_deceive_replacement)
```

```{r fig.width=5, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_deceive_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=2, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_deceive_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=2, more=T)),
  main="Variety", xlab="", ylab="")

```


### Delude

```{r}
m_long_delude_replacement <- glm(
  interpretator_verbal ~ year_c + variety, 
  data=all_data_replacement, subset=verb == "delude", family="binomial")

arm::display(m_long_delude_replacement)
```

```{r fig.width=5, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_delude_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=2, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_delude_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=2, more=T)),
  main="Variety", xlab="", ylab="")

```

### Fool

```{r}
m_long_fool_replacement <- glm(
  interpretator_verbal ~ year_c + variety, 
  data=all_data_replacement, subset=verb == "fool", family="binomial")

arm::display(m_long_fool_replacement)
```

```{r fig.width=5, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_long_fool_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=2, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_long_fool_replacement, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=2, more=T)),
  main="Variety", xlab="", ylab="")

```

