---
title: "R Notebook"
output: html_notebook
---



# Models for short-term diachronic perspective

```{r}
all_data <- read.csv("./data/all_data.csv", stringsAsFactors = T)
short_data <- subset(all_data, year >= 1990)

# recode drama -> spoken
short_data$genre[short_data$genre == "Drama"] <- "Spoken"
short_data$genre_short[short_data$genre_short == "dra"] <- "spo"
short_data <- droplevels(short_data)

str(short_data)
```

## Loss of interpretators

### Deceive

```{r}
m_short_deceive <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation + genre_short, 
  data=short_data, subset=verb == "deceive", family="binomial")

arm::display(m_short_deceive)
```

```{r fig.width=13, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_short_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=5, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_short_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=5, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_short_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=5, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_short_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=5, more=T)),
  main="Transitivity", xlab="", ylab="")

plot(effects::predictorEffect(
  "genre_short",
  m_short_deceive, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=5, nrow=1, ncol=5, more=F)),
  main="Genre", xlab="", ylab="")
```


### Delude

```{r}
m_short_delude <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation + genre_short, 
  data=short_data, subset=verb == "delude", family="binomial")

arm::display(m_short_delude)
```

```{r fig.width=13, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_short_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=5, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_short_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=5, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_short_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=5, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_short_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=5, more=T)),
  main="Transitivity", xlab="", ylab="")

plot(effects::predictorEffect(
  "genre_short",
  m_short_delude, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=5, nrow=1, ncol=5, more=F)),
  main="Genre", xlab="", ylab="")
```


### Fool

```{r}
m_short_fool <- glm(
  interpretator_present ~ year_c + variety + transitivity + negation + genre_short, 
  data=short_data, subset=verb == "fool", family="binomial")

arm::display(m_short_fool)
```

```{r fig.width=13, fig.height=3}
plot(effects::predictorEffect(
  "year_c",
  m_short_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response", lim=c(0,1))),
  lattice=list(array=list(row=1, col=1, nrow=1, ncol=5, more=T)),
  main="Year", xlab="")

plot(effects::predictorEffect(
  "variety",
  m_short_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=2, nrow=1, ncol=5, more=T)),
  main="Variety", xlab="", ylab="")

plot(effects::predictorEffect(
  "negation",
  m_short_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=3, nrow=1, ncol=5, more=T)),
  main="Negation", xlab="", ylab="")

plot(effects::predictorEffect(
  "transitivity",
  m_short_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=4, nrow=1, ncol=5, more=T)),
  main="Transitivity", xlab="", ylab="")

plot(effects::predictorEffect(
  "genre_short",
  m_short_fool, 
  confidence.level=.95), 
  axes=list(y=list(type="response",lim=c(0,1))),
  lattice=list(array=list(row=1, col=5, nrow=1, ncol=5, more=F)),
  main="Genre", xlab="", ylab="")
```